name: scientific_calc
description: A clean scientific calculator.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.3.1
  hive_flutter: ^1.1.0
  logger: ^1.1.0
  stacked: ^2.2.8
  stacked_hooks: ^0.2.1+1
  stacked_services: ^0.8.17
  stacked_themes: ^0.3.8+1

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2
  stacked_generator: ^0.5.7

flutter:
  uses-material-design: true
